//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication2.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wash Cloud is a unique Saudi innovation, designed
        ///for those who do not have enough time to wash
        ///their clothes or go to the traditional laundries. If
        ///you are looking for a convenient service and a
        ///unique experience to facilitate your daily schedule,
        ///then you are in the right place!.
        /// </summary>
        public static string AboutUsHomeText {
            get {
                return ResourceManager.GetString("AboutUsHomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizons Cloud are entrepreneurs aim to offer wide range of ready-made and customized digital solutions in many areas.
        ///By availing new flexible business models, we are determined to deliver products that are seemingly personalized to customers&apos; ambitions.
        ///
        ///Our customized solutions are designed to provide customers with the right products that can cover business gaps and meet their needs.
        /// As our name implies, our journey to unfold new Opportunities for development. We encourage innovative solutions to e [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutUsText {
            get {
                return ResourceManager.GetString("AboutUsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxes.
        /// </summary>
        public static string Boxes {
            get {
                return ResourceManager.GetString("Boxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning Services.
        /// </summary>
        public static string CleaningServices {
            get {
                return ResourceManager.GetString("CleaningServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Laundry.
        /// </summary>
        public static string CloudLaundry {
            get {
                return ResourceManager.GetString("CloudLaundry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfy.
        /// </summary>
        public static string Comfy {
            get {
                return ResourceManager.GetString("Comfy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfy Package.
        /// </summary>
        public static string ComfyPackage {
            get {
                return ResourceManager.GetString("ComfyPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conatct us.
        /// </summary>
        public static string Conatct_us {
            get {
                return ResourceManager.GetString("Conatct us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Info.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Always Here To Help
        ///
        ///Reach out to us through any of these support channels.
        /// </summary>
        public static string ContactText {
            get {
                return ResourceManager.GetString("ContactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we provide you with different packages that will suit your needs.
        /// </summary>
        public static string DifferentPackages {
            get {
                return ResourceManager.GetString("DifferentPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download our app.
        /// </summary>
        public static string DownloadOurApp {
            get {
                return ResourceManager.GetString("DownloadOurApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy Package.
        /// </summary>
        public static string EasyPackage {
            get {
                return ResourceManager.GetString("EasyPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;Your message was &lt;em&gt;not&lt;/em&gt; sent.&lt;/b&gt;&lt;/p&gt;.
        /// </summary>
        public static string FailedMessage {
            get {
                return ResourceManager.GetString("FailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message failed to send !!.
        /// </summary>
        public static string FailedMsg {
            get {
                return ResourceManager.GetString("FailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Us.
        /// </summary>
        public static string FindUs {
            get {
                return ResourceManager.GetString("FindUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Clients happiness is our sucess &quot;Wash Cloud&quot;.
        /// </summary>
        public static string FooterSaying {
            get {
                return ResourceManager.GetString("FooterSaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wash Cloud is the first cloud service of its kind in
        ///the Kingdom of Saudi Arabia. These laundry&apos;s
        ///cloud lockers are designed to serve gym goers and
        ///residents of modern residential complexes..
        /// </summary>
        public static string HomeText {
            get {
                return ResourceManager.GetString("HomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How the application works.
        /// </summary>
        public static string HowTheApplicationWorks {
            get {
                return ResourceManager.GetString("HowTheApplicationWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items type.
        /// </summary>
        public static string ItemsType {
            get {
                return ResourceManager.GetString("ItemsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laundry and Dry.
        /// </summary>
        public static string LaundryAndDry {
            get {
                return ResourceManager.GetString("LaundryAndDry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max per month.
        /// </summary>
        public static string MaxPerMonth {
            get {
                return ResourceManager.GetString("MaxPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to its available on apple store and google play.
        /// </summary>
        public static string OnStore {
            get {
                return ResourceManager.GetString("OnStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Locations.
        /// </summary>
        public static string OurLocations {
            get {
                return ResourceManager.GetString("OurLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providing smart laundry services with best
        ///practices that contribute to improving the quality
        ///of life for our customers with the acceleration of
        ///life..
        /// </summary>
        public static string OurMissionText {
            get {
                return ResourceManager.GetString("OurMissionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Partners.
        /// </summary>
        public static string OurPartners {
            get {
                return ResourceManager.GetString("OurPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are happy to be the first one&apos;s who provieded this serives , to help the customer to have thier laundry in the esiest , fastest and none human intercations, what makes us special is :.
        /// </summary>
        public static string OurService {
            get {
                return ResourceManager.GetString("OurService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Wash Cloud, you will never need to waste an
        ///hour of your day on washing or going twice to the
        ///traditional laundries, because we are existing in
        ///most of the facilities where you need to leave your
        ///clothes like gyms, to come back and find them
        ///clean, ready and always waiting for you..
        /// </summary>
        public static string OurServiceText {
            get {
                return ResourceManager.GetString("OurServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Vision:
        ///To be the first application in the Kingdom of Saudi
        ///Arabia for everything related to laundry..
        /// </summary>
        public static string OurVisionText {
            get {
                return ResourceManager.GetString("OurVisionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up time.
        /// </summary>
        public static string PickUpTime {
            get {
                return ResourceManager.GetString("PickUpTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing Plans.
        /// </summary>
        public static string PricingPlans {
            get {
                return ResourceManager.GetString("PricingPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;This Privacy Policy&lt;/b&gt; sets out the basis on which we will process any personal data, including without limitation, payment data, and other data we collect from you or from other sources or that you provide to us (&quot;Data&quot;) for your access and use of our store or mobile application (collectively the “Site”), services and applications (collectively, the “Services”).
        /// We understand the importance of this data, and we are committed to protecting and respecting your privacy. &lt;br/&gt;
        ///&lt;b&gt;Please read the followi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PrivacyText {
            get {
                return ResourceManager.GetString("PrivacyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put items.
        /// </summary>
        public static string PutItems {
            get {
                return ResourceManager.GetString("PutItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your routine, just got easier!.
        /// </summary>
        public static string QuoteText {
            get {
                return ResourceManager.GetString("QuoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug.
        /// </summary>
        public static string ReportABug {
            get {
                return ResourceManager.GetString("ReportABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety.
        /// </summary>
        public static string Safety {
            get {
                return ResourceManager.GetString("Safety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi Innovative Company.
        /// </summary>
        public static string SaudiInnovativeCompany {
            get {
                return ResourceManager.GetString("SaudiInnovativeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR.
        /// </summary>
        public static string ScanQR {
            get {
                return ResourceManager.GetString("ScanQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select branch.
        /// </summary>
        public static string Select_Branch {
            get {
                return ResourceManager.GetString("Select Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a message.
        /// </summary>
        public static string SendAMessage {
            get {
                return ResourceManager.GetString("SendAMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Your Message.
        /// </summary>
        public static string SendYourMessage {
            get {
                return ResourceManager.GetString("SendYourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01. great and amazing staff that will dilver the best service..
        /// </summary>
        public static string Service1 {
            get {
                return ResourceManager.GetString("Service1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02. easy and fast way to get your laundry..
        /// </summary>
        public static string Service2 {
            get {
                return ResourceManager.GetString("Service2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03. 24 hours customer support.
        /// </summary>
        public static string Service3 {
            get {
                return ResourceManager.GetString("Service3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up / Login.
        /// </summary>
        public static string SignUpOrLogIn {
            get {
                return ResourceManager.GetString("SignUpOrLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register using the phone number.
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the branch from the add order
        ///button at the bottom of the screen..
        /// </summary>
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the type of clothing for each
        ///item.
        /// </summary>
        public static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the pickup time within 7 hours in
        ///the morning or evening..
        /// </summary>
        public static string Step4 {
            get {
                return ResourceManager.GetString("Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will show you an image of a QR code
        ///for you, pass the code on the red light
        ///in the locker, to open an empty locker.
        /// </summary>
        public static string Step5 {
            get {
                return ResourceManager.GetString("Step5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put your clothes inside the closet, and
        ///they will be ready for the next visit..
        /// </summary>
        public static string Step6 {
            get {
                return ResourceManager.GetString("Step6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string Subscriptions {
            get {
                return ResourceManager.GetString("Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Your message sent successfully !!&lt;/p&gt;.
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was sent successfully !!.
        /// </summary>
        public static string SuccessMsg {
            get {
                return ResourceManager.GetString("SuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest an improvement.
        /// </summary>
        public static string SuggestAnImprovement {
            get {
                return ResourceManager.GetString("SuggestAnImprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonials.
        /// </summary>
        public static string Testimonials {
            get {
                return ResourceManager.GetString("Testimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Best Full Service.
        /// </summary>
        public static string TheBestFullService {
            get {
                return ResourceManager.GetString("TheBestFullService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The First .
        /// </summary>
        public static string TheFirst {
            get {
                return ResourceManager.GetString("TheFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The First Cloud Laundry Service.
        /// </summary>
        public static string TheFirstCloudLaundryService {
            get {
                return ResourceManager.GetString("TheFirstCloudLaundryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Top Ups.
        /// </summary>
        public static string TopUp {
            get {
                return ResourceManager.GetString("TopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 or 15.
        /// </summary>
        public static string TopUpItems {
            get {
                return ResourceManager.GetString("TopUpItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 73 or 110.
        /// </summary>
        public static string TopUpPrice {
            get {
                return ResourceManager.GetString("TopUpPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust.
        /// </summary>
        public static string Trust {
            get {
                return ResourceManager.GetString("Trust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlike others:.
        /// </summary>
        public static string UnlikeOthers {
            get {
                return ResourceManager.GetString("UnlikeOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you are going to deal with delivery laundries, it is
        ///no wonder that you will be surprised by the high
        ///prices of delivery or the change in pick-up and
        ///delivery times. We at Wash Cloud provide you
        ///with a flexible schedule via the application so that
        ///you can arrange and modify your appointments
        ///whenever you want..
        /// </summary>
        public static string UnlikeOthersText {
            get {
                return ResourceManager.GetString("UnlikeOthersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want more !!.
        /// </summary>
        public static string WantMore {
            get {
                return ResourceManager.GetString("WantMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wash Cloud Service.
        /// </summary>
        public static string WashCloudService {
            get {
                return ResourceManager.GetString("WashCloudService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Clients Say.
        /// </summary>
        public static string WhatClientsSay {
            get {
                return ResourceManager.GetString("WhatClientsSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What we offer.
        /// </summary>
        public static string WhatWeOffer {
            get {
                return ResourceManager.GetString("WhatWeOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to find us !!.
        /// </summary>
        public static string WhereToFindUs {
            get {
                return ResourceManager.GetString("WhereToFindUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Cloud Wardrobe!.
        /// </summary>
        public static string YourCloudWardrobe {
            get {
                return ResourceManager.GetString("YourCloudWardrobe", resourceCulture);
            }
        }
    }
}
